### ISSUE TITLE
Bit 11 of CALIB_DAC seems unset

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/pflib#63]
**Describe the bug**
Referencd in [elog note](https://aielisa19.cern.ch/elisa/display/403?logbook=LDMX-testbeam) and brought to my attention by @jmmans . Can see the effects in a 4/10 [elog post](https://aielisa19.cern.ch/elisa/api/LDMX-testbeam/messages/398/attachments/136). Great linearity up to a the bit-11 threshold, then drop down and start linearity up from 0 again.

**Expected behavior**
We don't want a jump discontinuity...

**Already Done**
I have checked the compiler code and saw basic validation that it seems to not be the issue:

```yaml
# calib_dac.yaml
reference_voltage_0:
  calib_dac: 0b100000000000
  intctest: 1
  extctest: 0
```
Then running `pfcompile --no-defaults calib_dac.yaml` produces
```
# This register settings file was generated by pfcompile
#    The columns are: page, register, value (in hex)
296,6,0x00
296,7,0x48
```
which is the expected result.
